services:
  - type: web
    name: broker-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
