services:
  - type: web
    name: brokers-api
    env: docker
    plan: free
    branch: main
    repo: https://github.com/SantiagoRuiDev/broker-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEVELOPMENT_PORT
        value: 3000
      - key: PRODUCTION
        value: "true"