import Joi from "joi";

export const agentSchema = Joi.object({
  codigo: Joi.string().required(),
  rol: Joi.string().required(),
  nombres: Joi.string().required(),
  apellidos: Joi.string().required(),
  correo: Joi.string().email().required(),
  estatus: Joi.string().required(),
  fecha_nacimiento: Joi.string().min(0).optional(),
  genero: Joi.string().min(0).optional(),
  ejecutivo_ciaros: Joi.string().min(0).optional(),
  nombre_de_comprobante: Joi.string().min(0).optional(),
  tipo_de_documento: Joi.string().min(0).optional(),
  tipo: Joi.string().min(0).optional(),
  ruc_de_comprobante: Joi.string().min(0).optional(),
  tipo_de_regimen: Joi.string().min(0).optional(),
  banda: Joi.string().min(0).optional(),
  numero_cuenta: Joi.string().min(0).optional(),
  codigo_de_beneficiario: Joi.string().min(0).optional(),
  tipo_de_cuenta: Joi.string().min(0).optional(),
  codigo_de_banco: Joi.string().min(0).optional(),
  telefono: Joi.string().min(0).optional(),
  nombre_de_beneficiario: Joi.string().min(0).optional(),
  direccion_de_beneficiario: Joi.string().min(0).optional(),
  ciudad_beneficiario: Joi.string().min(0).optional(),
  telefono_beneficiario: Joi.string().min(0).optional(),
  localidad_de_cobro: Joi.string().min(0).optional(),
  referencia: Joi.string().min(0).optional(),
  referencia_adicional: Joi.string().min(0).optional(),
  documento: Joi.string().min(0).optional(),
  ciudad: Joi.string().min(0).optional(),
  tarifa_comision: Joi.number().min(1).max(100).required(),
  liderId: Joi.any().optional(),
  iva: Joi.number().min(1).max(100).required(),
  ret_iva: Joi.number().min(1).max(100).required(),
  ret_renta: Joi.number().min(1).max(100).required(),
  gastos_adm: Joi.number().min(0).max(100).required(),
});
