import Joi from "joi";

export const agentSchema = Joi.object({
  id: Joi.string().optional(),
  codigo: Joi.string().required(),
  rol: Joi.string().required(),
  nombres: Joi.string().required(),
  apellidos: Joi.string().required(),
  correo: Joi.string().email().required(),
  estatus: Joi.string().required(),
  fecha_nacimiento: Joi.string().optional(),
  genero: Joi.string().optional(),
  ejecutivo_ciaros: Joi.string().optional(),
  nombre_de_comprobante: Joi.string().optional(),
  tipo_de_documento: Joi.string().optional(),
  ruc_de_comprobante: Joi.string().optional(),
  tipo_de_regimen: Joi.string().optional(),
  banda: Joi.string().optional(),
  iva: Joi.string().optional(),
  ret_iva: Joi.string().optional(),
  ret_renta: Joi.string().optional(),
  gastos_adm: Joi.string().optional(),
  executivoCiarios: Joi.number().optional(),
  tipo_de_pago: Joi.string().optional(),
  numero_cuenta: Joi.string().optional(),
  numero_secuencial: Joi.string().optional(),
  numero_de_comprobante: Joi.string().optional(),
  codigo_de_beneficiario: Joi.string().optional(),
  moneda: Joi.string().optional(),
  valor: Joi.string().optional(),
  tipo_de_cuenta: Joi.string().optional(),
  numero_de_cedula: Joi.string().optional(),
  codigo_de_banco: Joi.string().optional(),
  telefono: Joi.string().optional(),
  nombre_de_beneficiario: Joi.string().optional(),
  direccion_de_beneficiario: Joi.string().optional(),
  ciudad_beneficiario: Joi.string().optional(),
  telefono_beneficiario: Joi.string().optional(),
  localidad_de_cobro: Joi.string().optional(),
  referencia: Joi.string().optional(),
  referencia_adicional: Joi.string().optional(),
  cedula: Joi.string().optional(),
  ciudad: Joi.string().optional(),
  forma_de_pago: Joi.string().optional(),
  tarifa_comision: Joi.number().optional(),
  liderId: Joi.string().optional(),
});
